---
- name: Manage BIG-IP systems
  hosts:  tag_Name_big_ip
  tasks:
    - name: Collect BIG-IP facts
      bigip_facts:
        server: "{{ BIGIP_SERVER }}"
        user: "{{ BIGIP_USER }}"
        password: "{{ BIGIP_PASSWORD }}"
        include: "interface,vlan"
      delegate_to: localhost
