---
- name: Manage BIG-IP systems
  connection: local
  hosts:  tag_Name_big_ip
  tasks:
    - name: Collect BIG-IP facts
      bigip_facts:
        server: "{{ inventory_hostname }}"
        user: "{{ BIGIP_USER }}"
        password: "{{ BIGIP_PASSWORD }}"
        include: "interface,vlan"
        validate_certs: "false"
      delegate_to: localhost
